### ISSUE TITLE
A sincere request to know the use of Altium as the schematic and PCB editor

### ISSUE THREAD

**Issue by amalinda** [BCMmodule/Hardware#3]
Dear All,

I am so exited to see this project and thank you all who made this possible. Although I would like to know why an opensource software such as KiCad is not used to create this project. it would be lovely if we too could contribute this project. Unfortunately we don't have Altium. I hope you will consider using an open source PCB/Schematic editor for your future projects as moving this to KiCad will be a lot of effort. If there is a particular reason Altium was used, it will be lovely to know. 

Thank you all.

**Comment by BCMmodule** [comment]
Amalinda,

Thank you for your message. We are really happy to get positive feedback like yours! We still keep pushing to make a lot of things happen, just like for example extended temperature range as a feature. 

As to your question about why we did not use KiCad or other it is a very simple question: Because they are not as good as commercial tools these days. There might come a time when this changes. In the meantime we are in touch with many developers who are willing to contribute to the project. Maybe there will be a
KiCad version in future - but it will be provided by the community and not directly by us. As professionals who get paid for hardware development we will stick with Altium for now. We love Open Source but we do not wholly rely on Open Source to create Open Source. ;-)

Best regards
BeagleCore.com

**Comment by BCMmodule** [comment]
By the way: There is a converter for Altium to KiCad <https://github.com/thesourcerer8/altium2kicad>.
